project:
  type: website
  output-dir: docs

website:
  title: "The Itchen Bridge"
  page-navigation: false
      #- href: index.qmd

format:
  html:
    theme: 
      light: [lux] #, styles.scss]
      dark: [lux] # , dark.scss]
    css: photo-slider.css
    toc: true
    page-layout: full
    title-block-banner: true
    title: "The Itchen Bridge"
    author: "Alistair Bailey, Pardeep Panesar and Hannah Wake"
    date: last-modified
    date-format: "[Last Updated on] YYYY-MM-DD"
    bibliography: references.bib
    
editor: visual
