project:
  type: website
  output-dir: docs
  render:
     - index.qmd

website:
  title: "The Itchen Bridge"
  page-navigation: false
  google-analytics: "G-D21LFNS7LB"
format:
  html:
    theme: 
      light: [lux, styles.scss]
      dark: [lux, dark.scss]
    toc: true
    page-layout: full
    title-block-banner: true
    title: "The Itchen Bridge"
    subtitle: "Construction in colour"
    author: "Alistair Bailey, Pardeep Panesar, Kiki Kuijjer,<br>Jeremy Hayes and Hannah Wake"
    date: last-modified
    date-format: "[Last Updated on] YYYY-MM-DD"
    bibliography: references.bib
    lightbox: true
    link-external-icon: true
    link-external-newwindow: true
    appendix-style: none
    number-sections: true
    csl: nature.csl
    
editor: visual
