project:
  type: website
  output-dir: docs

website:
  title: "The Itchen Bridge"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: 
      light: [lumen, styles.scss]
      dark: [lumen, dark.scss]
    css: photo-slider.css
    toc: true
    page-layout: full
    #title-block-banner: true
    author: "Alistair Bailey, Pardeep Panesar and Hannah Wake"
    date: last-modified
    date-format: "[Last Updated on] YYYY-MM-DD"
    bibliography: references.bib
    
editor: visual

